// AUTO-GENERATED by vite-plugin-typed-routes — do not edit manually
import type { RouteRecordInfo } from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    RouteNamedMap: {
      'companies-list': RouteRecordInfo<'companies-list', '/companies', Record<never, never>, Record<never, never>>
      'users-list': RouteRecordInfo<'users-list', '/users', Record<never, never>, Record<never, never>>
      'user-detail': RouteRecordInfo<'user-detail', '/users/:id', { id: number }, { id: number }>
    }
  }
}

export interface RouteQueryMap {
  'companies-list': { search?: string; industry?: string }
  'users-list': Record<never, never>
  'user-detail': Record<never, never>
}
